name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.18"

      - run: uv build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - run: npx changelogithub@0.13
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
